### ISSUE TITLE
Controller component not working while pinging even if its container i.e. controller0 is healthy and active 

### ISSUE THREAD

**Issue by Suraez** [IntelliSys-Lab/RainbowCake-ASPLOS24#1]
## Environment details:
OS: Ubuntu 22.04.4 LTS (jammy jellyfish)
Python Version: 3.9.0
RAM: 32 GB
Disk: 256 GB
CPU cores: 20

In the last task of the **_ansible/roles/controller/tasks/deploy.yml_** i.e. **_wait until the Controller in this host is up and running_**, i am getting this following error:

`fatal: [controller0]: FAILED! => {"attempts": 12, "changed": false, "content": "", "elapsed": 0, "msg": "Status code was -1 and not [200]: Request failed: <urlopen error [Errno 111] Connection refused>", "redirected": false, "status": -1, "url": "https://172.17.0.1:10001/ping"}`

Upon inspection of the **_controller_** container logs,  i found this:

![image](https://github.com/IntelliSys-Lab/RainbowCake-ASPLOS24/assets/45430290/7984459f-e007-42b0-9ab5-1c99247e331b)

The same issues is opened on official OpenWhisk repo which can be found [here](https://github.com/apache/openwhisk/issues/5331): I couldn't find the solution for this issues. If anyone faced this issue and has solved it, please let me know. 

Thank you.

**Comment by serein-dream** [comment]
Hi, have you solved it yet? I encountered the same problem and tried all the methods online, but none of them worked

**Comment by Suraez** [comment]
> Hi, have you solved it yet? I encountered the same problem and tried all the methods online, but none of them worked

No, but i spawn up a cloud VM (Ubuntu 22.04 LTS with Python version 3.9) and ./setup.sh ran to completion luckily. You can try this.

**Comment by hanfeiyu** [comment]
This seems to be the problem of OpenWhisk setup, not from RainbowCake side. But I'm glad that you managed to solve the problem.

Feel free to open the issue if you have further questions.
