### ISSUE TITLE
HTTP handler (language runtime)

### ISSUE THREAD

**Issue by huang-jl** [IntelliSys-Lab/RainbowCake-ASPLOS24#2]
Hello, when I am reading the code, I cannot find the implementation of http handler. As in the paper, it said:

> Upon receiving an Init HTTP request, the container proxy first creates an Action folder under user home directory and installs user packages (import user code from database, activate libraries, and set environment variables) under it. We add a Clean HTTP handler to delete the Action directory and unset all user-defined environment variables.

I wonder where is the implementation of this http handler in this repository?

Looking forward to your reply, thanks!

**Comment by hanfeiyu** [comment]
The HTTP handlers are implemented in OpenWhisk's [runtime proxy](https://github.com/apache/openwhisk-runtime-go/tree/master/openwhisk), which is embedded in all the runtime Docker images. These Docker images are [pulled from Docker Hub](https://github.com/IntelliSys-Lab/RainbowCake-ASPLOS24/blob/master/ansible/files/runtimes.json#L15-L62 ) during OpenWhisk setup and are publicly available.  

For most runtime images, OpenWhisk will first build a [golang-based runtime proxy](https://github.com/apache/openwhisk-runtime-go/tree/master/openwhisk) that processes HTTP requests before compiling the language runtime itself. Here is an [example](https://github.com/apache/openwhisk-runtime-python/blob/f707898000353c0fcb879f182d5a18956e5b013c/core/python310Action/Dockerfile#L18-L35) of how OpenWhisk builds the proxy when compiling the Python 3.10 runtime.

The HTTP handlers described in the paper follow the style of [the handlers in OpenWhisk's original runtime proxy](https://github.com/apache/openwhisk-runtime-go/blob/a26f27a393278d06a82db2a7ccdfe6968f07e0c7/openwhisk/actionProxy.go#L167-L174). We are still working on sanitizing the runtime repos that build the Docker images and trying to make them public. 

Feel free to reopen the issue if you have further questions.

**Comment by huang-jl** [comment]
Thanks for your quick reply!
