### ISSUE TITLE
Inquiry about Reproducing RainbowCake on Existing OpenWhisk Deployment

### ISSUE THREAD

**Issue by Assassin141** [IntelliSys-Lab/RainbowCake-ASPLOS24#5]
I have deployed OpenWhisk on a three-node Kubernetes cluster following the README of [OpenWhisk](https://github.com/apache/openwhisk-deploy-kube/blob/master/README.md). I did not deploying OpenWhisk using Ansible, however.

I would like to know if it is possible to reproduce RainbowCake on my existing deployment of OpenWhisk. Could you please provide additional guidance on deploying distributed RainbowCake?

**Comment by hanfeiyu** [comment]
Thank you for your question. However, I'm not able to provide any suggestions with k8s-based OpenWhisk, as I don't have much experience deploying OpenWhisk on k8s. The code logic is implemented in OpenWhisk's own components and is not associated with k8s.
