### ISSUE TITLE
Which openwhisk commit version do you use?

### ISSUE THREAD

**Issue by ActivePeter** [IntelliSys-Lab/RainbowCake-ASPLOS24#6]

**Comment by hanfeiyu** [comment]
This is the latest OpenWhisk [commit](https://github.com/apache/openwhisk/commit/e65f899ca5ce95d1aadd8f1b244a2cb80bbd35f4) I can track from our internal repo.

**Comment by ActivePeter** [comment]
> This is the latest OpenWhisk [commit](https://github.com/apache/openwhisk/commit/e65f899ca5ce95d1aadd8f1b244a2cb80bbd35f4) I can track from our internal repo.

Thanks a lot
